<?php
namespace frontend\components;

use Yii;
use yii\rbac\DbManager;


class RBACmng extends DbManager
{
  public function checkAccess($userId, $permissionName, $params = [])
  {
    if(in_array($permissionName,Yii::$app->params['defaultAccess'])) {
      return true;
    };
    //if($permissionName);
    return parent::checkAccess($userId, $permissionName, $params); // TODO: Change the autogenerated stub
  }

}