<?php
namespace frontend\components;

use Yii;
use yii\rbac\DbManager;


class RBACmng extends DbManager
{
  public function checkAccess($userId, $permissionName, $params = [])
  {

    if($permissionName=="ChooseCafe"){
      $cafe_list=Yii::$app->user->identity->cafes;
      if(count($cafe_list))return false;
    }

    if(in_array($permissionName,Yii::$app->params['defaultAccess'])) {
      return true;
    };
    //if($permissionName);
    return parent::checkAccess($userId, $permissionName, $params); // TODO: Change the autogenerated stub
  }

}