<?php
namespace frontend\components;


use frontend\modules\users\models\Users;
use Yii;
use yii\db\Query;
use yii\web\View;
use yii\helpers\Url;
use yii\twig\ViewRenderer;
use common\components\SdViewBASE;


class ViewBASE extends View
{

  public $all_params = [];
  public $first_init = true;
  public $description;
  public $h1;
  public $meta_head;

  public $contentBD;

  public $user_id = false;
  public $user = [];

  public function init_param()
  {
    $this->first_init = false;

    if (!Yii::$app->user->isGuest) {
      $this->user_id = Yii::$app->user->id;
      $user = Yii::$app->user->identity;
      $this->user = (array)$user->getIterator();

      $this->all_params['user'] = (array)$user->getIterator();
      $this->all_params['user_id'] = Yii::$app->user->id;

    }

    $request = Yii::$app->request;
    if ($request->isAjax) {
      return;
    }
  }


  public function render($view, $params = [], $context = null)
  {
    if ($this->first_init) {
      $this->init_param();
    }

    $this->all_params = array_merge($this->all_params, $params);
    if ($this->all_params && isset($this->all_params['exception'])) {
      Yii::$app->params['exception'] = $this->all_params['exception'];
    };
    Yii::$app->params['all_params'] = $this->all_params;

    $tags = '';
    foreach (Yii::$app->view->metaTags as $meta) {
      $tags .= $meta;
    }
    preg_match_all('/<[\s]*meta[\s]*(name|property)="?' . '([^>"]*)"?[\s]*' . 'content="?([^>"]*)"?[\s]*[\/]?[\s]*>/si', $tags, $match);
    $tags = [];
    foreach ($match[2] as $k => $name) {
      $tags[$name] = $match[3][$k];
    }
    Yii::$app->view->metaTags = [];


    if(isset($this->all_params['title'])) {
      $this->title = $this->all_params['title'];
    }
    if(isset($this->all_params['description'])) {
      $this->description = $this->all_params['description'];
    }

    //d($this->title);
    //ddd($tags);
    $params = array_merge((array)$this, $this->all_params);
    unset($this->all_params['all_params']);
    return parent::render($view, $params, $context); // TODO: Change the autogenerated stub
  }

  public function afterRender($viewFile, $params, &$output)
  {
    if ($this->first_init) {
      $this->init_param();
    }
    $this->all_params = array_merge($this->all_params, $params);
    Yii::$app->params['all_params'] = $this->all_params;
    unset($this->all_params['all_params']);

    parent::afterRender($viewFile, $params, $output); // TODO: Change the autogenerated stub
    //ddd($this->all_params);
    $output = Yii::$app->TwigString->render(
        $output,
        $this->all_params
    );
  }
}