<?php

namespace frontend\modules\cafe\models;

use Yii;

/**
 * This is the model class for table "cafe_params".
 *
 * @property int $id
 * @property string $name
 * @property string $vat_list
 * @property string $time_zone
 * @property string $datetime
 * @property string $datetime_js
 * @property string $date
 * @property string $date_js
 * @property string $time
 * @property string $time_js
 *
 * @property Cafe[] $caves
 */
class CafeParams extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cafe_params';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['show_sum'], 'integer'],
            [['name'], 'string', 'max' => 20],
            [['vat_list'], 'string', 'max' => 1000],
            [['time_zone', 'datetime', 'datetime_js', 'date', 'date_js', 'time', 'time_js'], 'string', 'max' => 30],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'vat_list' => Yii::t('app', 'Vat List'),
            'time_zone' => Yii::t('app', 'Time Zone'),
            'datetime' => Yii::t('app', 'Datetime'),
            'datetime_js' => Yii::t('app', 'Datetime Js'),
            'date' => Yii::t('app', 'Date'),
            'date_js' => Yii::t('app', 'Date Js'),
            'time' => Yii::t('app', 'Time'),
            'time_js' => Yii::t('app', 'Time Js'),
            'show_sum' => Yii::t('app', 'Show sum'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCaves()
    {
        return $this->hasMany(Cafe::className(), ['params_id' => 'id']);
    }

  public function beforeSave($insert)
  {
    Yii::$app->cache->flush();
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }
}
