<?php

namespace frontend\modules\cafe\models;

use Yii;

/**
 * This is the model class for table "cafe".
 *
 * @property int $id
 * @property string $name
 * @property int $max_person
 * @property string $address
 * @property string $tps_code
 * @property string $tvq_code
 * @property int $last_task
 * @property double $tps_value
 * @property double $tvq_value
 * @property int $franchisee
 *
 * @property Polls[] $polls
 * @property UserCafe[] $userCafes
 * @property UserTimetable[] $userTimetables
 */
class Cafe extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cafe';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'params_id'], 'required'],
            [['name', 'address','currency','timeZone'], 'trim'],
            [['name', 'address','currency','timeZone','vat_value'], 'string'],
            [['max_person', 'last_task', 'franchisee'], 'integer'],
          ["logo","image"]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'max_person' => Yii::t('app', 'Max Person'),
            'address' => Yii::t('app', 'Address'),
            'last_task' => Yii::t('app', 'Last Task'),
            'franchisee' => Yii::t('app', 'Franchisee'),
            'currency' => Yii::t('app', 'Currency'),
            'timeZone' => Yii::t('app', 'time Zone'),
        ];
    }


  public function beforeValidate()
  {
    if (!parent::beforeValidate()) {
      return false;
    }

    if ($this->isNewRecord) {
      if (Yii::$app->user->isGuest) {
        $this->franchisee = 1;
      } else if (!Yii::$app->user->can('AllFranchisee')) {
        $this->franchisee = Yii::$app->user->identity->franchisee;
      }
    }

    return true;
  }

  public function afterSave($insert, $changedAttributes)
  {
    Yii::$app->cache->delete("cafe_params_".$this->id);
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  /**
     * @return \yii\db\ActiveQuery
     */
    public function getPolls()
    {
        return $this->hasMany(Polls::className(), ['cafe_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserCafes()
    {
        return $this->hasMany(UserCafe::className(), ['cafe_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParam()
    {
      return $this->hasOne(CafeParams::className(), [ 'id'=>'params_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserTimetables()
    {
        return $this->hasMany(UserTimetable::className(), ['cafe_id' => 'id']);
    }
}
